name: Docker Image CI

on: [push]

jobs:
  build_rest_api:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.6'

    - run: pip install -r requirements.txt -r requirements-test.txt
    - run: PYTHONPATH=. pytest
    - name: "Build and publish Docker image"
      uses: elgohr/Publish-Docker-Github-Action@2.12
      with:
        name: "${{ github.repository }}/currency_converter"
        username: "${{ secrets.DOCKER_REGISTRY_LOGIN }}"
        password: "${{ secrets.DOCKER_REGISTRY_PASSWORD }}"
        registry: docker.pkg.github.com
